[versions]
kotlin_core = "2.2.10"
me_crypto = "2.2.10-1.1.0"
kotlin_browser = "0.5.0"

[libraries]
me-crypto = { module = "tk.mallumo:crypto", version.ref = "me_crypto" }
kotlin-browser = { module = "org.jetbrains.kotlinx:kotlinx-browser", version.ref = "kotlin_browser" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin_core" }
